# MD013/line-length - Line length
MD013: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements: [a]

# MD045/no-alt-text - Images should have alternate text (alt text)
MD045: false
